In [3]:
import numpy as np
from sympy import Abs
from sympol import Polytope
from sympol.ehrhart import h_star_to_ehrhart_polynomial, h_to_gamma_vector

filename = "../.data/4p_reflexive_cs.txt"

# iterate over all reflexive polytopes with 4 vertices, one per line
i = 0
set_gammadiff = set()
for line in open(filename):
    # parse the line
    vertices = eval(line)
    p = Polytope(vertices)
    hp = p.h_star_vector
    pts_p = p.integer_points
    print(i)
    is_minimal = True
    for v in p.vertices:
        # avoid removing the same vertices twice
        nzv = [a for a in v if a != 0]
        if nzv[0] < 0:
            continue
        pts_q = [tuple(u) for u in pts_p]
        v1 = tuple(v)
        v2 = tuple(-v)
        pts_q.remove(v1)
        pts_q.remove(v2)
        q = Polytope(pts_q)
        if q.dim < p.dim or not q.contains(q._origin(), strict=True):
            continue
        if not q.is_reflexive:
            continue
        is_minimal = False
        minimals.append(p)
        hq = q.h_star_vector
        hdiff = tuple(np.array(hp) - np.array(hq))
        gammadiff = h_to_gamma_vector(hdiff, p.dim)
        set_gammadiff.add(gammadiff)
        print(gammadiff)
    print()
    i += 1

# print the number of different gamma vectors
print(minimals)
        

0

1

2
(0, 2, 0, 0, 0)
(0, 2, 0, 0, 0)

3
(0, 2, 8, 0, 0)
(0, 2, 8, 0, 0)
(0, 2, 8, 0, 0)
(0, 2, 8, 0, 0)

4
(0, 2, 0, 0, 0)
(0, 2, 0, 0, 0)
(0, 2, 0, 0, 0)
(0, 2, 0, 0, 0)

5
(0, 2, 0, 0, 0)
(0, 2, 0, 0, 0)
(0, 2, 0, 0, 0)

6
(0, 2, 12, 0, 0)
(0, 2, 12, 0, 0)
(0, 2, 12, 0, 0)
(0, 2, -4, 0, 0)
(0, 2, 12, 0, 0)

7
(0, 2, 6, 0, 0)
(0, 2, 6, 0, 0)
(0, 2, 6, 0, 0)
(0, 2, 6, 0, 0)
(0, 2, 6, 0, 0)

8
(0, 2, 0, 0, 0)
(0, 2, 0, 0, 0)
(0, 2, 0, 0, 0)
(0, 2, 0, 0, 0)

9
(0, 2, 0, 0, 0)
(0, 2, 0, 0, 0)
(0, 2, 0, 0, 0)

10
(0, 2, 4, 0, 0)

11
(0, 2, 8, 0, 0)
(0, 2, 8, 0, 0)
(0, 2, -2, 0, 0)
(0, 2, 4, 0, 0)
(0, 2, 8, 0, 0)

12
(0, 2, 4, 0, 0)
(0, 2, 8, 0, 0)
(0, 2, 8, 0, 0)
(0, 2, 8, 0, 0)
(0, 2, 4, 0, 0)

13
(0, 2, 2, 0, 0)
(0, 2, 2, 0, 0)
(0, 2, 2, 0, 0)
(0, 2, 8, 0, 0)
(0, 2, 2, 0, 0)

14
(0, 2, 0, 0, 0)
(0, 2, 0, 0, 0)
(0, 2, 0, 0, 0)
(0, 2, 0, 0, 0)

15
(0, 2, 4, 0, 0)
(0, 2, 4, 0, 0)
(0, 2, 8, 0, 0)
(0, 2, 8, 0, 0)
(0, 2, 8, 0, 0)

16
(0, 2, 8, 0, 0)
(0, 2, 8, 0, 0)
(0, 2, 8, 0, 0)
(0, 2, 0,

In [ ]:
import itertools

k = 4
d = 10

for g in range(3, 10):
    print(g)
    for last_v in itertools.product(range(g), repeat=d-1):

        discard = False
        for i in range(d-2):
            if last_v[i] > last_v[i+1]:
                discard = True
        
        if discard:
            continue
        
        verts = np.zeros((d, d), dtype=int)
        for i in range(d-1):
            verts[i, i] = 1
        verts[d-1, :] = np.array(list(last_v) + [g])

        verts = np.concatenate([verts, -verts])
        p = Polytope(vertices=verts)

        if p.is_reflexive:
            print(list(last_v) + [g])
            print(p.h_star_vector)
            print(p.gamma_vector)
            print("--------")

# [0, 0, 0, 0, 0, 0, 0, 0, 1, 2]
# (1, 14, 77, 232, 434, 532, 434, 232, 77, 14, 1)
# (1, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0)
# --------
# [0, 0, 0, 0, 0, 0, 1, 1, 1, 2]
# (1, 10, 61, 216, 450, 572, 450, 216, 61, 10, 1)
# (1, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0)
# --------
# [0, 0, 0, 0, 1, 1, 1, 1, 1, 2]
# (1, 10, 45, 184, 466, 636, 466, 184, 45, 10, 1)
# (1, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0)
# --------
# [0, 0, 1, 1, 1, 1, 1, 1, 1, 2]
# (1, 10, 45, 120, 466, 764, 466, 120, 45, 10, 1)
# (1, 0, 0, 0, 256, 0, 0, 0, 0, 0, 0)
# --------
# [1, 1, 1, 1, 1, 1, 1, 1, 1, 2]
# (1, 10, 45, 120, 210, 1276, 210, 120, 45, 10, 1)
# (1, 0, 0, 0, 0, 1024, 0, 0, 0, 0, 0)
# --------


In [1]:
from sympol import Polytope
from sympol.ehrhart import h_star_vector_of_cartesian_product_from_h_star_vectors, h_to_gamma_vector, gamma_to_h_vector

minimals = [
    [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [1, 1, 1, 2], [-1, -1, -1, -2], [0, 0, -1, 0], [0, -1, 0, 0], [-1, 0, 0, 0]],
    [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [0, 0, 0, -1], [0, 0, -1, 0], [0, -1, 0, 0], [-1, 0, 0, 0]],
    [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 1, 2], [0, 0, -1, -2], [0, 0, -1, 0], [0, -1, 0, 0], [-1, 0, 0, 0]],
    [[1, 0, 0, 0], [0, 1, 0, 0], [0, 1, 2, 0], [1, 0, 0, 2], [-1, 0, 0, -2], [0, -1, -2, 0], [0, -1, 0, 0], [-1, 0, 0, 0]],
    [[1, 0, 0, 0], [1, 2, 0, 0], [1, 0, 2, 0], [1, 0, 0, 2], [-1, 0, 0, -2], [-1, 0, -2, 0], [-1, -2, 0, 0], [-1, 0, 0, 0]],
    [[1, 0, 0, 0], [0, 1, 0, 0], [0, 1, 2, 0], [0, 1, 0, 2], [0, -1, 0, -2], [0, -1, -2, 0], [0, -1, 0, 0], [-1, 0, 0, 0]],
]

all_cs = dict()

for verts_p in minimals:
    p = Polytope(vertices=verts_p)
    pd = p.dual
    npts = pd.n_integer_points

    pd_nf = frozenset([tuple(w) for w in pd.vertices])
    if npts not in all_cs:
        all_cs[npts] = set((pd_nf,))
    else:
        all_cs[npts].add(pd_nf)

current_np = max(all_cs.keys())

while current_np > 0:
    if current_np not in all_cs:
        current_np = current_np-1
        continue
    for verts in all_cs[current_np]:
        p = Polytope(vertices=list(verts))
        p_pts = p.integer_points
        for v in verts:
            # avoid removing the same vertices twice
            nzv = [a for a in v if a != 0]
            if nzv[0] < 0:
                continue

            # remove the vertex and its opposite
            v_plus = tuple([a for a in v])
            v_minus = tuple([-a for a in v])
            new_verts = [u for u in p_pts if tuple(u) not in [v_plus, v_minus]]
            assert len(new_verts) == len(p_pts) - 2

            # check if the new polytope is full dimensional and canonical
            q = Polytope(new_verts)
            assert q.is_centrally_symmetric
            if q.dim < p.dim or not q.contains(q._origin(), strict=True):
                continue

            np_q = q.n_integer_points
            q_nf = frozenset([tuple(w) for w in q.vertices])
            if np_q not in all_cs:
                all_cs[np_q] = set((q_nf,))
            else:
                all_cs[np_q].add(q_nf)

    for np in sorted(all_cs.keys()):
        print(np, len(all_cs[np]))
    print()
            
    current_np = current_np-1


17 1
25 1
27 1
41 1
45 1
79 8
81 1

17 1
25 1
27 1
41 1
45 1
77 60
79 8
81 1

17 1
25 1
27 1
41 1
45 1
75 312
77 60
79 8
81 1

17 1
25 1
27 1
41 1
45 1
73 1350
75 312
77 60
79 8
81 1



KeyboardInterrupt: 

In [4]:
import numpy as np
from sympy import Abs
from sympol import Polytope, Point
from sympol.ehrhart import h_star_to_ehrhart_polynomial, h_to_gamma_vector
from itertools import combinations

filename = "../.data/4p_reflexive_cs.txt"

# iterate over all reflexive polytopes with 4 vertices, one per line
i = 0
set_gammadiff = set()
for line in open(filename):
    # parse the line
    vertices = eval(line)
    p = Polytope(vertices)
    verts = list(p.vertices)

    # iterate over all pairs of vertices
    o = Point([0] * p.dim)
    for v1, v2, v3 in combinations(verts, p.dim-1):
        
        print(o, v1, v2, v3)
    
    break

[0 0 0 0] [1 0 0 0] [0 1 0 0] [0 0 1 0]
[0 0 0 0] [1 0 0 0] [0 1 0 0] [1 1 1 2]
[0 0 0 0] [1 0 0 0] [0 1 0 0] [-1 -1 -1 -2]
[0 0 0 0] [1 0 0 0] [0 1 0 0] [0 0 -1 0]
[0 0 0 0] [1 0 0 0] [0 1 0 0] [0 -1 0 0]
[0 0 0 0] [1 0 0 0] [0 1 0 0] [-1 0 0 0]
[0 0 0 0] [1 0 0 0] [0 0 1 0] [1 1 1 2]
[0 0 0 0] [1 0 0 0] [0 0 1 0] [-1 -1 -1 -2]
[0 0 0 0] [1 0 0 0] [0 0 1 0] [0 0 -1 0]
[0 0 0 0] [1 0 0 0] [0 0 1 0] [0 -1 0 0]
[0 0 0 0] [1 0 0 0] [0 0 1 0] [-1 0 0 0]
[0 0 0 0] [1 0 0 0] [1 1 1 2] [-1 -1 -1 -2]
[0 0 0 0] [1 0 0 0] [1 1 1 2] [0 0 -1 0]
[0 0 0 0] [1 0 0 0] [1 1 1 2] [0 -1 0 0]
[0 0 0 0] [1 0 0 0] [1 1 1 2] [-1 0 0 0]
[0 0 0 0] [1 0 0 0] [-1 -1 -1 -2] [0 0 -1 0]
[0 0 0 0] [1 0 0 0] [-1 -1 -1 -2] [0 -1 0 0]
[0 0 0 0] [1 0 0 0] [-1 -1 -1 -2] [-1 0 0 0]
[0 0 0 0] [1 0 0 0] [0 0 -1 0] [0 -1 0 0]
[0 0 0 0] [1 0 0 0] [0 0 -1 0] [-1 0 0 0]
[0 0 0 0] [1 0 0 0] [0 -1 0 0] [-1 0 0 0]
[0 0 0 0] [0 1 0 0] [0 0 1 0] [1 1 1 2]
[0 0 0 0] [0 1 0 0] [0 0 1 0] [-1 -1 -1 -2]
[0 0 0 0] [0 1 0 0] [0 0 1 0] [0 0